In [1]:
import numpy as np
from matplotlib import pyplot as plt
import imageio

In [2]:
# Test reshape.
x = np.arange(12).reshape((3,4))
y = np.arange(3).reshape((3,1))
print('x:',x,'y:',y,'x+y:',x+y,sep='\n')

x:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
y:
[[0]
 [1]
 [2]]
x+y:
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [3]:
# Test uniform distribution.
print(np.random.uniform(size=(3,1)))

[[0.04740376]
 [0.13524605]
 [0.65602964]]


In [8]:
tile_test = range(3)
np.tile(tile_test, [5, 2])

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [21]:
# Meshgrid test
x = y = np.linspace(-2,2,5)
X,Y = np.meshgrid(x,y)
print(f"X:\n{X}")
print(f"Y:\n{Y}")

X:
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
Y:
[[-2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.]]


In [2]:
# Create data for unit sphere to save as file
res = 640
x = y = np.linspace(-2, 2, res)
X, Y = np.meshgrid(x, y)
# Returns function values
# f(x,y) = { sqrt(1 - (x**2 + y**2)) + 1    if x**2 + y**2 <= 1,
#          { 0                              otherwise.
def unit_sphere(x, y):
    z_vals = (1 - (x**2 + y**2))
    neg_mask = z_vals < 0
    z_vals[neg_mask] = 0
    z_vals = np.sqrt(z_vals) + 1
    z_vals[neg_mask] = 0
    return z_vals
# Nonzero values are between 1 and 2.
Z = unit_sphere(X, Y)
# Make values between 0 and 256.
sphere = ((Z / 2) * 256).astype(np.uint8)

# Print data and save file "sphere.png".

# print(np.min(Z), np.max(Z))
# print(np.min(sphere), np.max(sphere))

# imageio.imwrite('sphere.png', sphere)

# plt.pcolormesh(X,Y,Z, cmap='gray')
# plt.axis('equal')
# plt.show()

In [1]:
# Test offsets
h = (.35**2 + .5**2)**.5 + .125
print(h)

0.7353277807866851
